GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_auto_fund TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_mig_prepaid_loans TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_user_group TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_user_profile TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_wss_ref_mapping TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_baseline_image TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_funding_env TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_auto_fund_parameters TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_baseline_portfolio TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_funding_stage TO LOANIQ_INTERFACES_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON rbsgbl_amend_comments TO LOANIQ_INTERFACES_ROLE;

GRANT SELECT ON rbsgbl_funding_msg_seq TO LOANIQ_INTERFACES_ROLE;


GRANT EXECUTE ON rbsgbl_proc_fund_amend_cmnt TO LOANIQ_INTERFACES_ROLE;
GRANT EXECUTE ON rbsgbl_proc_fund_auto_cmnt TO LOANIQ_INTERFACES_ROLE;
GRANT EXECUTE ON rbsgbl_proc_fund_auto_conf TO LOANIQ_INTERFACES_ROLE;
GRANT EXECUTE ON RBSGBL_PROC_FUND_DEALER_LIST TO LOANIQ_INTERFACES_ROLE;
GRANT EXECUTE ON rbsgbl_proc_fund_lock_record TO LOANIQ_INTERFACES_ROLE;
GRANT EXECUTE ON RBSGBL_PROC_FUND_NARRATIVE TO LOANIQ_INTERFACES_ROLE;

GRANT SELECT ON rbsgbl_auto_fund TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_mig_prepaid_loans TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_user_group TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_user_profile TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_wss_ref_mapping TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_baseline_image TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_funding_env TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_auto_fund_parameters TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_baseline_portfolio TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_funding_stage TO LOANIQ_READONLY_ROLE;
GRANT SELECT ON rbsgbl_amend_comments TO LOANIQ_READONLY_ROLE;

GRANT SELECT ON rbsgbl_funding_stage TO LOANIQ_RECONCILIATION_ROLE;