/*
Module	:	Funding Interfaces
Author	:   Jagjit Singh
Date	:	18/03/2009	
Purpose	:	Creating Indexes on Funding Tables.
*/

DROP INDEX UGT_CDE_GROUP_IN;      
CREATE INDEX UGT_CDE_GROUP_IN       ON  RBSGBL_USER_GROUP(UGT_CDE_GROUP);
DROP INDEX ACT_RID_FUND_REQ_IND;  
CREATE INDEX ACT_RID_FUND_REQ_IND   ON RBSGBL_AMEND_COMMENTS(ACT_RID_FUND_REQ); 
DROP INDEX API_STATIC_VALUES_IND; 
CREATE INDEX API_STATIC_VALUES_IND  ON RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, STATIC_VALUE_1,STATIC_VALUE_2,STATIC_VALUE_3);
DROP INDEX AFT_RID_FUND_REQ_IND  ;
CREATE INDEX AFT_RID_FUND_REQ_IND   ON RBSGBL_AUTO_FUND(AFT_RID_FUND_REQ);
DROP INDEX FST_RID_FUND_REQ_IND  ;
CREATE INDEX FST_RID_FUND_REQ_IND   ON RBSGBL_FUNDING_STAGE(FST_RID_FUND_REQ);
DROP INDEX FST_RID_COMB_IND      ;
CREATE INDEX FST_RID_COMB_IND       ON RBSGBL_FUNDING_STAGE(FST_RID_OUTSTANDNG,FST_CDE_BRANCH,FST_CDE_EXPENSE,FST_CDE_PORTFOLIO,FST_WSS_MAP_REF,FST_CDE_AMEND_STATUS);
DROP INDEX BPT_CDE_COMB_IND      ;
CREATE INDEX BPT_CDE_COMB_IND       ON RBSGBL_BASELINE_PORTFOLIO(BPT_WSS_MAP_REF,BPT_RID_OUTSTANDNG,BPT_CDE_BRANCH,BPT_CDE_EXPENSE,BPT_CDE_PORTFOLIO,BPT_PCT_RATE,BPT_DTE_CYCLE_STRT,BPT_DTE_CYCLE_END);
DROP INDEX BPT_RID_OUTSTANDNG_IND;
CREATE INDEX BPT_RID_OUTSTANDNG_IND ON RBSGBL_BASELINE_IMAGE(BIT_RID_OUTSTANDNG);  