/*
Module	:	Funding Interface
Author	:	Manish Jain
Date	:	04 Feb 2008
Purpose	:	incr-2329.sql. Funding Static Details document to reflect the WSS counterparties setup as per production.
			For STATIC_TYPE_ID = 'FND01'
*/

DELETE FROM RBSGBL_STATIC_DETAILS WHERE STATIC_TYPE_ID = 'FND01';

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GBMCB','RBLQLGBM','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GDIST','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GLEGC','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS1','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS2','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS3','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS4','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS5','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GRBS6','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GSMTN','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTROR','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR01','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR02','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR03','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR04','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR05','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR06','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR07','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR08','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR09','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR10','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR11','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR12','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR13','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR14','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR15','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR16','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR17','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR18','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR19','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR20','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR21','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','GTR22','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','IAS39','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','PIRAS','RBLQPIR','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','RTAIL','RBLQRET','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','TRADE','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKASF','RBLQASF','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKCB ','RBLQUKCB','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKFIM','RBLQCBFM','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKPRF','RBLQPRF','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKSHP','RBLQSHIP','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLN','UKWRH','RBLQTRAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GBMCB','NWLQGBM','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB1','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB2','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB3','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB4','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB5','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','GNWB6','NWLQTRAD','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','RTAIL','NWLQRET','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','UKASF','NWLQASF','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','UKCB ','NWLQUKCB','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','NWBLN','UKFIM','NWLQLFM','NWLCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSPR ','GBMCB','RBLQBPA','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSFF ','GBMCB','RBLQBFF','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSML ','GBMCB','RBLQMIL','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSMD','GBMCB','RBLQMAD','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSOS','GBMCB','RBLQOSLO','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSHS','GBMCB','RBLQBHE','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSLB','GBMCB','RBLQBLS','LONCTY');
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND01','RBSSH','GBMCB','RBLQSTCK','LONCTY');


DELETE FROM rbsgbl_static_details where static_type_id = 'FND06' AND KEY_VALUE_1 = 'RBSSH' AND  KEY_VALUE_2 = 'UPPMT';

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND06','RBSSH','UPPMT','Unscheduled Loan Principal Payment','');

DELETE FROM rbsgbl_static_details where static_type_id = 'FND08' AND KEY_VALUE_1 IN ('03','51');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND08','03','','ACK-FAIL','');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID,KEY_VALUE_1,KEY_VALUE_2, STATIC_VALUE_1, STATIC_VALUE_2) VALUES('FND08','51','','Missing Internal area','');

COMMIT;

SELECT COUNT(*) FND01_COUNT FROM RBSGBL_STATIC_DETAILS WHERE STATIC_TYPE_ID = 'FND01';


