/*
Module	:	Funding Interface
Author	:	Manish Jain
Date	:	18 Dec 2008
Purpose	:	Insert statement for static details to include updated counteparty values for STATIC_TYPE_ID = 'FND06.'
*/

delete from RBSGBL_STATIC_DETAILS where static_type_id = 'FND06' AND KEY_VALUE_2 IN ('PRDCR', 'MIG');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','NWBLN','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBMDL','PRDCR','Loan Conversion from Existing (Part of Repricing)');
     
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSFF','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSHS','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSLB','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSLN','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSMD','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSML','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSOS','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSPR','PRDCR','Loan Conversion from Existing (Part of Repricing)');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSSH','PRDCR','Loan Conversion from Existing (Part of Repricing)');


INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','NWBLN','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBMDL','MIG','Migration Approach');
     
INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSFF','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSHS','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSLB','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSLN','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSMD','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSML','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSOS','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSPR','MIG','Migration Approach');

INSERT INTO RBSGBL_STATIC_DETAILS(STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1) 
VALUES ('FND06','RBSSH','MIG','Migration Approach');

COMMIT;