DELETE FROM RBSGBL_STATIC_DETAILS
WHERE STATIC_TYPE_ID = 'FND04'
AND KEY_VALUE_1 = 'RBSFF     '
AND KEY_VALUE_2 = 'OEKB      ';

 INSERT INTO RBS_LIQ.RBSGBL_STATIC_DETAILS 
 ( STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, KEY_VALUE_3,
 STATIC_VALUE_1, STATIC_VALUE_2, STATIC_VALUE_3, STATIC_VALUE_4,
 STATIC_VALUE_5 ) 
 VALUES 
 ( 'FND04', 'RBSFF     ', 'OEKB      ', NULL, 'OeKB Financing Rate                                       '
 , 'N                                                 ', NULL, NULL, NULL);