DELETE FROM RBSGBL_STATIC_DETAILS
WHERE STATIC_TYPE_ID = 'FND04'
AND KEY_VALUE_1 = 'RBSFF     '
AND KEY_VALUE_2 = 'GTCSP     ';
                                                
DELETE FROM RBSGBL_STATIC_DETAILS
WHERE STATIC_TYPE_ID = 'FND04'
AND KEY_VALUE_1 = 'RBSFF     '
AND KEY_VALUE_2 = 'OEKB      ';