/*
Module	:	Funding Interface
Author	:	Manish Jain
Date	:	20 Oct 2008
Purpose	:	Update statement for static details to include updated counteparty values for STATIC_TYPE_ID = 'FND01.'
*/
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 =' '  WHERE STATIC_TYPE_ID = 'FND01';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGBMCB'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GBMCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGLEGC'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GLEGC';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGRBS1'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GRBS1';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGRBS2'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GRBS2';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGRBS3'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GRBS3';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNGTROR'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'GTROR';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNRTAIL'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'RTAIL';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNTRADE'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'TRADE';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKASF'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKASF';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKCB'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKFIM'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKFIM';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKPRF'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKPRF';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKSHP'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKSHP';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLNUKWRH'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLN' AND KEY_VALUE_2 = 'UKWRH';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='NWLQLNGNWB1'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'NWBLN' AND KEY_VALUE_2 = 'GNWB1';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='NWLQLNRTAIL'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'NWBLN' AND KEY_VALUE_2 = 'RTAIL';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='NWLQLNUKASF'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'NWBLN' AND KEY_VALUE_2 = 'UKASF';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='NWLQLNUKCB'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'NWBLN' AND KEY_VALUE_2 = 'UKCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='NWLQLNUKFIM'  WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'NWBLN' AND KEY_VALUE_2 = 'UKFIM';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQPRGBMCB' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSPR' AND KEY_VALUE_2 = 'GBMCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQFFGBMCB' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSFF' AND KEY_VALUE_2 = 'GBMCB';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQMLGBMCB' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSML' AND KEY_VALUE_2 = 'GBMCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQMDGBMCB' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSMD' AND KEY_VALUE_2 = 'GBMCB';

UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQOSNORDC' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSOS' AND KEY_VALUE_2 = 'NORDC';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQHSNORDC' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSHS' AND KEY_VALUE_2 = 'NORDC';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQLBGBMCB' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSLB' AND KEY_VALUE_2 = 'GBMCB';
UPDATE RBSGBL_STATIC_DETAILS SET STATIC_VALUE_1 ='RBLQSHNORDC' WHERE STATIC_TYPE_ID = 'FND01' AND KEY_VALUE_1 = 'RBSSH' AND KEY_VALUE_2 = 'NORDC';


