/*
Module	:	LoanIQ Interfaces
Author	:       Manish Jain
Date	:	07-10-2008
Purpose	:	
*/



ALTER TABLE RBSGBL_BASELINE_portfolio ADD BPT_AMT_SETTLE NUMBER(31,15) DEFAULT 0.0;



ALTER TABLE RBSGBL_BASELINE_portfolio ADD BPT_IND_SETTLE VARCHAR2(1) DEFAULT 'N';




ALTER TABLE RBSGBL_FUNDING_STAGE ADD FST_RID_LINK_TRAN VARCHAR2(8) DEFAULT '';




ALTER TABLE RBSGBL_FUNDING_STAGE ADD FST_AMT_INTEREST NUMBER(31,15) DEFAULT 0.0;


ALTER TABLE RBSGBL_FUNDING_STAGE ADD FST_TXN_COF_RID VARCHAR2(8) DEFAULT '';



ALTER TABLE rbsgbl_baseline_portfolio RENAME COLUMN BPT_RID_OST_TRAN TO BPT_RID_TRAN;

COMMIT;

