/*
Module	:	Funding Interfaces
Author	:       Jai Jain
Date	:	27-02-2009
Purpose	:	TD#2423 
	        Corporate Bonds need to be included in the Funding interface extract to WSS
	        Inserting records in static_details table
*/


INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND01', 'RBSLN', 'GSDL3', 'RBLQTRAD','LONCTY')
/    
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND01', 'RBSLN', 'GSDL4', 'RBLQTRAD','LONCTY')
/   
 INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND01', 'RBSLN', 'GSDL5', 'RBLQTRAD','LONCTY')
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values
   ('FND01', 'NWBLN', 'IAS39', 'NWLQTRAD','NWLCTY')  
/  
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSLN', 'CORP', 'Corporate Bonds','CBLT')  
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSLN', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'NWBLN', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'NWBLN', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSPR', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSPR', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSFF', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSFF', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSML', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSML', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSMD', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSMD', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSMDL', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSMDL', 'LEASE', 'Lease','CBLT')
/   
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSOS', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSOS', 'LEASE', 'Lease','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSHS', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSHS', 'LEASE', 'Lease','CBLT')
/   
 INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSLB', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSLB', 'LEASE', 'Lease','CBLT')
/   
 INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSSH', 'CORP', 'Corporate Bonds','CBLT')   
/
INSERT INTO RBSGBL_STATIC_DETAILS
   (STATIC_TYPE_ID, KEY_VALUE_1, KEY_VALUE_2, STATIC_VALUE_1,STATIC_VALUE_2)
 Values  
   ('FND03', 'RBSSH', 'LEASE', 'Lease','CBLT')
/
COMMIT
/