/*
Module	:	Funding Interfaces
Author	:    Manish Jain
Date	:	03/11/2008	
Purpose	:	Inserting Data in  RBSGBL_FUNDING_ENV
*/

DELETE FROM RBSGBL_FUNDING_ENV WHERE ZONE_NAME = 'ZONE2';

INSERT INTO RBSGBL_FUNDING_ENV ( ZONE_NAME, OST_POLLER_TIME,
ACCR_CYCLE_POLLER_TIME ) VALUES ( 
'ZONE2',  TO_Date( '09/05/2008 11:06:32 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '09/05/2008 11:06:32 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
commit;
 
